kind: Deployment
apiVersion: apps/v1
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: ft-services-phpmyadmin:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
