apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: ft-services-wordpress
        image: "ft-services-wordpress"
        imagePullPolicy: Never