kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: ft-services-wordpress:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
      nodePort: 5050
