apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ft-services-ftps:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: ft-services-tls
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftps
      port: 21
      protocol: TCP
      targetPort: 21
  externalIPs:
    - {{MINIKUBEIP}}
